### ISSUE TITLE
problem with add widget

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#24]
Hi once again,

Is there anyway to add a widget in a dashboard using by (Id) of widget

**Comment by jaumard** [comment]
Hi, 

No it's not possible, and it doesn't make sense because if your widget is already under the dashboard it's already added. You can't put a widget outside the dashboard tag and then add it into the dashboard if it's what you're trying to achieve. In that case you remove the one outside and re create it with same params when you add it to dashboard

**Comment by waleed-sarwar** [comment]
I've 2 dashboards and i want to remove widget from 1 dashboard which is possible and **add into other dashboard** 

i just tried to get widget from getWidgetById and pass into addItem function but it gives error
i also tried to use add widget and it adds into dashboard but while deleting it gives error
any other way 

![image](https://user-images.githubusercontent.com/30215747/28405100-569f3552-6d45-11e7-9d44-dd7e00178d67.png)
