### ISSUE TITLE
When size is not an integer (i.e 1.2, 1.8) the height allocate wrong margin

### ISSUE THREAD

**Issue by evandrogrm** [jaumard/ngx-dashboard#42]
Hi, great component,
When i put some size like the tittle, the size of margin allocate the height/width wrong.
Demo here: https://stackblitz.com/edit/angular-mw3s1w?file=src%2Fapp%2Fapp.component.html
Image:
![screenshot_20180924_173256](https://user-images.githubusercontent.com/6799983/45977657-a71d4580-c020-11e8-8878-12d1920c8e28.png)

**Comment by jaumard** [comment]
Hello :) 

Thanks for the report but this is by design :) size needs to be integer for the algorithm to work. It's a simple algorithm that create a proportional grid, allowing floating size will break the "proportional" effect as widgets will have whatever size. It will change the all purpose of the library and the all algorithm will need to be rewrite to allow this as widget will be able to be positioned at multiple x and y.

on your example it's only the height that is a float, this can be done quite easily but a nightmare with the current algorithm if you want to support this for width too. I think if you start supporting float it should be for both width and height... 

Feel free to create your own dashboard library with a Floating size algorithm, if my code can be a starting point it's cool but the main part will be the algorithm so I'm not sure it will help you a lot.
